### ISSUE TITLE
To do list for milestone2

### ISSUE THREAD

**Issue by liuyuwei169** [UBC-MDS/us-police-shootings-analysis#4]
So the things we are trying to do:
- [x] 1. do the map app and make sure it works
- [x] 2. do other secondary plots <- done with histogram with ages. Later will improve it by doing other plots.
- [x] 3. submit on github.com and shinyapps.io. Make sure they work.
- [x] 4. document the functionality of your Shiny app in a markdown document
- [x] 5. INCLUDE SCREENSHOTS illustrating all of the functions your Shiny app performs.
- [x] 6. do the write-up. Develope a code of conduct

**Comment by adityashrm21** [comment]
completed all tasks
